
const Main = {render(){return 'main'}}
const routes= [
    {
        path:'/',
        component:()=>import('../components/home.vue'),
       
    },
    {
        path:'/card',
        name:'card',
        component:()=>import('../components/card.vue'),
        meta:{
            name:'小火车',
            show:true
        }
    },
    {
        path:'/aircraft',
        name:'aircraft',
        component:()=>import('../components/aircraft.vue'),
        meta:{
            name:'飞机'
        }
    },
    {
        path:'/watch',
        name:'watch',
        component:()=>import('../components/watch-demo.vue'),
        meta:{
            name:'watch示例和router跳转'
        }
    },
    {
        path:'/computed',
        name:'computed',
        component:()=>import('../components/computed.vue')
    },
    {
        path:'/watchEffect',
        name:'watchEffect',
        component:()=>import('../components/watchEffect.vue'),
        meta:{
            name:'watchEffect示例'
        }
    },
    {
        path:'/father',
        name:'father',
        component:()=>import('../components/father.vue'),
        meta:{
            name:'父子传参'
        }
    },
    {
        path:'/v-model-demo',
        name:'v-model-demo',
        component:()=>import('../components/v-model-demo.vue'),
        meta:{
            name:'v-model'
        }
    },
    {
        path:'/provide-demo',
        name:'provide-demo',
        component:()=>import('../components/provide-demo.vue'),
        meta:{
            name:'provide-inject'
        }
    },
    {
        path:'/pinia-demo',
        name:'pinia-demo',
        component:()=>import('../components/pinia-demo.vue'),
        meta:{
            name:'pinia测试'
        }
    },
    {
        path:'/keepAlive-demo',
        name:'keepAlive-demo',
        component:()=>import('../components/keepAlive-demo.vue'),
        meta:{
            name:'keepAlive-demo'
        }
    },
    {
        path:'/showSom',
        name:"showSom",
        component:()=>import('../components/showSom.vue'),
        meta:{
            name:'showSom'
        }
    },
    {
        path:'/some-keep',
        name:"some-keep",
        component:()=>import('../components/some-keep.vue')
    },
    {
        path:'/keep-demo',
        name:"keep-demo",
        component:()=>import('../components/keep-demo.vue')
    },
]
export default routes